// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aatktfwnqzkntpcgcisb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdGt0ZnducXprbnRwY2djaXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDk2NDIsImV4cCI6MjA2OTUyNTY0Mn0.ZAWDEUW5SIIMdXlOqhA2JpJpjzDn-XW8wh0qRhEO3q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});